### ISSUE TITLE
接口无数据返回，连接被拒绝

### ISSUE THREAD

**Issue by and1990** [xumaohuai/Flutter-CuriosityApp#2]
E/flutter (17036): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (17036): DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Connection refused, errno = 111, address = app3.qdaily.com, port = 33002

**Comment by xumaohuai** [comment]
不会出现这种情况吧,你是Android还是iOS

**Comment by and1990** [comment]
不好意思回复晚了。

运行环境：macbookpro
模拟器：android，api26

**Comment by itcloudy** [comment]
我也出现了一样的问题，macpro android虚拟机

登录请求
```

Future<LoginToken> loginAccount(Map<String, String> params) async {
  BaseResponse<LoginToken> response =
      await HttpUtil().post<LoginToken>(ServerAPI.loginUrl, data: params);
  return response.data;
}
```
封装的请求
```
Future<BaseResponse<T>> post<T>(url, {data, options, cancelToken}) async {
    Response response;
    int _code;
    String _message;
    T _data;

    response = await _dio.post(
      url,
      data: data,
      cancelToken: cancelToken,
    );
    if (response.statusCode == HttpStatus.ok) {
      try {
        if (response.data is Map) {
          _message = response.data[_messageKey];
          _data = response.data[_dataKey];
          _code = (response.data[_codeKey] is String)
              ? int.tryParse(response.data[_codeKey])
              : response.data[_codeKey];
        } else {
          Map<String, dynamic> _dataMap = _decodeData(response);
          _code = (_dataMap[_codeKey] is String)
              ? int.tryParse(_dataMap[_codeKey])
              : _dataMap[_codeKey];
          _message = _dataMap[_messageKey];
          _data = _dataMap[_dataKey];
        }
        return BaseResponse(_code, _message, _data);
      } catch (e) {
        return new Future.error(new DioError(
          response: response,
          message: "data parsing exception...",
          type: DioErrorType.RESPONSE,
        ));
      }
    }
    return new Future.error(new DioError(
      response: response,
      message: "data parsing exception...",
      type: DioErrorType.RESPONSE,
    ));
  }

```
调用
```
Future<LoginToken> token = loginAccount(
                      {"username": _username, "password": _password});
                  print(token);
```
错误
```
I/flutter ( 8277): Instance of 'Future<LoginToken>'
E/flutter ( 8277): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 8277): NoSuchMethodError: The method 'post' was called on null.
E/flutter ( 8277): Receiver: null
E/flutter ( 8277): Tried calling: post<dynamic>("/login/account", cancelToken: null, data: _LinkedHashMap len:2)
E/flutter ( 8277): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 8277): #1      HttpUtil.post (package:flutter_erp/services/base.dart:59:27)
```

**Comment by hcj-life** [comment]
我今天也遇到这个问题了。上周五还可以登录的，今天跑起来就会报上述错误。请问这个什么原因呢。
运行环境：win7 vscode
华为荣耀7i，6.0.1

**Comment by edison0951** [comment]
应该是这个API被屏蔽了

**Comment by XkSuperCool** [comment]
我也遇到了这个问题，请问您解决了吗？😥
